name: Weekly Calendar Update

on:
  schedule:
    - cron: '0 12 * * MON'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Установка зависимостей
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Генерация календаря
        run: python scraper.py --max-movies 30
      - name: Commit and Push calendar.ics
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add calendar.ics
          if git diff --staged --quiet; then
            echo "Нет изменений в календаре"
          else
            git commit -m "📅 Еженедельное обновление календаря $(date +'%Y-%m-%d %H:%M UTC')"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
